#spring:
#  redis:
#    host: localhost
#    port: 6379
info:
  auth:
    tokenPrefix: test
    overdueTime: 9999999999
    domain: localhost
    exclude: true
    cacheInitialCapacity: 100
    cacheMaximumSize: 200
    cacheStats: true
    loadingCache: false